spring:
  application:
    name: teddies

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
#    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:teddies
    username: {USERNAME}
    password: {PASSWORD}
    driver-class-name: org.h2.Driver

server:
  port: 9000